# configuration settings for gossipd


# Directories used by the program
# base directory
GossipDir = "c:\\gossipd"					

# where the user puts their peers to send to
SendPeers = "c:\\gossipd\\sendpeers"		

# where the user puts their peers to receive from
RecvPeers = "c:\\gossipd\\recvpeers"		

# where to put new keys that are generated by the rsa.py script
KeyDir = "c:\\gossipd\\keys"				


# User information
myIP = "10.20.50.77"			# should be this computer, use the showmyip.py script to check
port = 13001					# port to listen to, must be between 1 and 65535
nick = "PeterL"					# nick of the user

showbuttons = True
sockettimeout = 4


####-- The following settings have not been implemented yet. --####
PING = True 			# (True/False) -- wether to send out pings 
PINGINTERVAL = 500.0 	# (seconds: float) -- seconds to wait before sending pings
PONG = True 			# (True/False) -- wether to respond to pings
HISTORY = 60.0 			# (seconds: float) -- maximum age of messages to respond with when update requested
GENKEYS = True 			# (True/False) -- wether to generate more keys
BogusPct = 0.1			# fraction of generated keys to mark as bogus
SendQuitMessage	= False # wether to send a message when you leave
QuitMessage = "%s has quit." % (nick)		
